### ISSUE TITLE
move functionality into package extensions

### ISSUE THREAD

**Issue by cjdoris** [JuliaPy/PythonCall.jl#405]
Can probably make these into weak dependencies:
- Serialization
- Dates
- Tables
- Markdown??
- Pkg??
- REPL??

Also:
- ~~make PyCall a weak dependency?~~ Done!
- ~~remove Requires?~~ Done!
- ~~require Julia 1.9? or just have older versions be less compatible? or use PackageExtensionCompat?~~ Done!

**Comment by cjdoris** [comment]
The deps are now:
```toml
[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UnsafePointers = "e17b2a0c-0bdf-430a-bd0c-3a23cae4ff39"
```

These are mostly stdlibs (Dates, Libdl, Markdown, Serialization) or core functionality (CondaPkg, Preferences, UnsafePointers).

What remains are:
- MacroTools - this is purely internal, and could be replaced with other tools for pattern-matching on code. Not breaking.
- Tables - this is a lightweight interface package. We cannot remove it or put it into an extension without removing `pytable`. So we'll keep it.

All in all, there is nothing left to do on this issue.
